ral-facilities/scigateway

.travis.yml
README.md
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/strings.test.tsx

I fixed a linting error and a unit test failure that only failed on Ubuntu machines (a promise wasn't being returned, which meant the `await` inside the test wasn't catching the inner promise resolution). Additionally, I added the badges to the README
Closes #4 and closes #6

Fix CI and finish setting up CI & codecov

---

cypress/integration/login.spec.ts
package.json
src/authentication/icatAuthProvider.test.tsx
src/authentication/icatAuthProvider.tsx
src/authentication/testAuthProvider.tsx
src/loginPage/__snapshots__/loginPage.component.test.tsx.snap
src/loginPage/loginPage.component.test.tsx
src/loginPage/loginPage.component.tsx
src/setupTests.js
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/state.types.tsx
src/stories/loginPage.stories.tsx
yarn.lock

This PR adds the icatAuthProvider and adds the ability for the login page to show a dropdown based off of the mnemonics fetched from `scigateway-auth`.
This PR relies on ral-facilities/scigateway-auth#36
Closes #129 
Part of #18

Feature/icat auth #129

---

src/loginPage/loginPage.component.tsx

Fixes the bug (#135) that Goel found that selecting a new mnemonic retriggers a call to `/authenticators`
Fixes #135

#135 - check length of mnemonics before querying for authenticators

---

codecov.yml

To stop codecov from assigning a failed status to commits and PRs due to too strict thresholds, actually set thresholds. I've set the project one to be compared against the master branch but to allow a less than 5% decrease, as well as setting code in PRs themselves to be ok as long as the PR coverage is 90%+.
Do these limits seem ok? Is the PR limit too high? We can always ignore codecov commit/PR statuses and merge anyway if there is a reason for missed coverage.

Set codecov targets + thresholds

---

src/loginPage/loginPage.component.tsx

Use a boolean variable to track whether we have already tried to fetch the mnemonics so as to prevent spamming the user with error messages.
Closes #138

Fix multiple ICAT authenticator error messages

---

src/App.tsx

Set `disableGlobal` to `true` in the class name generate provided to Material UI
Closes #146

Fix Material-UI styling clashes with plugins

---

package.json
src/authentication/icatAuthProvider.test.tsx
src/authentication/icatAuthProvider.tsx
src/authentication/parseJwt.test.ts
src/authentication/parseJwt.ts

This PR parses the returned JWT and sets the username of the user from the JWT payload. This results in the user profile component showing the username.
This relies on ral-facilities/scigateway-auth#40
Closes #143

#143 - parse jwt + set username in icat authenticator

---

src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/authorisedRoute.component.tsx
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx

This fixes the plugin remounting issue described in #145, via implementing the solution I described here: https://github.com/ral-facilities/scigateway/issues/145#issuecomment-581833290. This is due to the DAaaS project preferring the current toggle-able behaviour rather than an overlay, so this just fixes the base issue of using a memoised component.
Fixes #145

Fix uneccessary plugin remounting

---

src/notifications/__snapshots__/notificationBadge.component.test.tsx.snap
src/notifications/notificationBadge.component.tsx
src/theming.tsx

Added an override to MuiBadge theming that replaces how the notification badge was currently being coloured and allows DG badges to use the same colour.
connect to #440, ral-facilities/datagateway#415, ral-facilities/datagateway#419

override MuiBadge style for colorPrimary #440

---

public/res/default.json
public/settings.example.json
server/e2e-settings.json
src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
src/mainAppBar/__snapshots__/userProfile.component.test.tsx.snap
src/mainAppBar/mainAppBar.component.test.tsx
src/mainAppBar/mainAppBar.component.tsx
src/mainAppBar/userProfile.component.test.tsx
src/mainAppBar/userProfile.component.tsx

Moved the options for darkmode and cookies to a seperate menu outside of the user/account menu so they can be accessed without logging in.
EDIT:
In light of ral-facilities/datagateway#430 have added the settings button to the tour/help.
EDIT:
connect to #426

moved browser settings to new menu #426

---

src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/authorisedRoute.component.test.tsx
src/routing/authorisedRoute.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx
src/state/state.types.tsx

Added `startUrl` to `settings.json` as an optional setting. When provided, if one of the plugins has the same `link` as `startUrl`, and the current path is the homepage (`/`), then a redirect to the plugin will be triggered.
If the user needs to login, the referring path will be the plugin link, so after the login redirect the plugin will be loaded.
If the user is already logged in, then a redirect is needed to ensure the plugin renders the updated path (and not what it would show for a path of `/`. This happens at the same place as the login redirect (if the `startUrl` is enabled).
If `startUrl` is not set, or no plugin matches the url, then nothing should happen (previous behaviour maintained).
connect to #427, …

allow optional redirect to plugin from homepage #427

---

src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/scigateway.types.tsx
src/tour/tour.component.tsx

Add optional `helpSteps` to the plugin payload and register the contents for the tour. Retain the previous `helpText` (which only applies to the plugin in the navbar itself) to maintain compatibility if the plugins haven't been updated.
Testing the new `helpSteps` will require code from ral-facilities/datagateway#430 (PR ral-facilities/datagateway#442)
connect to #442 ral-facilities/datagateway#430

allow plugins to register helpSteps #442

---

.github/workflows/ci-build.yml

Triggers the CI build workflow when a PR is merged into master. It was noticed that that the CI build workflow builds only PRs and not branches. This means that master is not tested when something is merged and therefore the status badge does not work.
A merge into master results into a push commit to master, therefore the proposed changes should address this "issue".
closes #525

Trigger CI build workflow when a PR is merged into Master

---

public/res/default.json
src/__snapshots__/pageContainer.test.tsx.snap
src/footer/__snapshots__/footer.component.test.tsx.snap
src/footer/footer.component.test.tsx
src/footer/footer.component.tsx
src/pageContainer.component.tsx
src/routing/routing.component.tsx

Adds a footer component that displays external links that direct the user to the facility home, cookie policy and about us pages. To allow facilities to configure these external links and their names, a raw HTML is stored in in the `default.json` file. I noticed that the link names change colour after they have been clicked (which is normal behaviour), so I just wanted to get people's view on whether we want to override this? It seems that is overridden in TopCAT and `text-decoration` is set to `none` to remove the lines under the link names. Given that there are some hyperlinks in the _Cookies_ page, it might better to globalise this if we want the same behaviour there.
The footer component is not tested as I wanted to check whether what I have done so far meets the requirements before …

Add footer to display external links at bottom of pages

---

src/App.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx

Prevents identical banners and notification from being displayed multiple times. Refer to the issue for background information and before screenshots.
closes #542

Prevent duplicate banners from displaying multiple times

---

.github/workflows/release-build.yml

This adds an actions workflow that runs for master and all tags that:
- Runs `yarn build`
- Creates a tarball from the `build` directory
- If triggered by a push / PR to master, updates the snapshot tag to point to master
- Creates a release and adds the tarball to the release

Add actions workflow for creating releases

---

src/App.test.tsx
src/loginPage/loginPage.component.test.tsx

Calling `singleSpa.start()` prevents warnings when running the unit tests.
closes #613

Add singleSpa.start() to relevant tests #613

---

cypress/integration/login.spec.ts
src/authentication/baseAuthProvider.tsx
src/authentication/githubAuthProvider.test.tsx
src/authentication/icatAuthProvider.test.tsx
src/authentication/jwtAuthProvider.test.tsx
src/state/reducers/scigateway.reducer.test.tsx

Keeps the user logged in after refreshing the web page or navigating to a different address. On page refresh, when auth provider is constructed in code, a check is made for an existing token. If one is found, the user details are parsed from it and stored in code. Otherwise, user is assumed not to be logged in.
No additional data is stored locally, relies on the token being secure and signed. Any changes to the token made by the user invalidate the session and log the user out. This prevents the user from modifying their username or admin status.
Also amending test data in auth provider test code to use a valid JWT as test data instead of the string 'token'. This is to allow for testing to be carried out to confirm user login. The code is unable to parse user details from a token string …

Persistent login between page refreshes/re-routing #641

---

src/adminPage/__snapshots__/adminPage.component.test.tsx.snap
src/adminPage/adminPage.component.test.tsx
src/adminPage/adminPage.component.tsx
src/cookieConsent/cookieConsent.component.test.tsx
src/cookieConsent/cookiesPage.component.test.tsx
src/example.component.test.tsx
src/loginPage/loginPage.component.test.tsx
src/mainAppBar/userProfile.component.test.tsx
src/maintenancePage/maintenancePage.component.test.tsx
src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.test.tsx
src/navigationDrawer/navigationDrawer.component.tsx
src/notifications/notificationBadge.component.test.tsx
src/pageContainer.test.tsx
src/preloader/preloader.component.test.tsx
src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/authorisedRoute.component.test.tsx
src/routing/authorisedRoute.component.tsx
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/scigateway.types.tsx
src/state/strings.test.tsx

Allows for DataGateway admin routes to be created if `"admin": true` is added to the route object in the `*-settings.json` file. Protects such routes so that only admins can access them by checking whether the user is admin or not and by not creating links to them in the navigation drawer. Displays the `PageNotFound` page if a non-admin user navigates to an admin route. This functionality is needed for the Admin Download table that will be created in DataGateway Download as part of the [Add TopCAT admin download table](https://github.com/ral-facilities/datagateway/issues/613) issue. In preparation for this work, I created two tabs in the Admin page - _Maintenance_ and _Admin Download_. The former is active by default and its panel displays the maintenance text boxes that admins can use to …

Display admin functionality from plugins

---

src/routing/routing.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/scigateway.types.tsx

Fixes the bug where plugins would sometimes not be loaded when loaded directly (e.g. when trying to load `/browse/investigation`). This bug was discovered due to the changes in dataview to allow plugin routes to be configurable, which meant they were loaded later on after the plugin settings files were loaded which then revealed this issue. This PR fixes the issue by checking if we are on a "potential plugin route" (i.e. any route that scigateway doesn't know about) and listening for the register route event from the plugin that corresponds to our current location. I also added a 3 second timeout to this listening, as otherwise the site would never load if someone navigated to a route that should 404.
Additionally, since I was looking at `scigateway.actions.test.tsx`, I had a look at the …

Bugfix/fix plugin loading #732

---

src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.test.tsx
src/navigationDrawer/navigationDrawer.component.tsx

This addresses a couple of small changes to the navigation drawer requested from a recent demo of SciGateway. The requests are described in the issue and aim to improve readability and reduce clutter.
A summary of changes is as follows:
- reduced spacing between menu headings and sub headings
- DataGateway logo now appears only once on the nav drawer: at the top
- centered all elements (arguably looks better but let me know your thoughts)
- changed colour of section headings from secondary theme color (grey) to primary theme color (black) 
For reference, here are some comparison images.
Current navigation drawer (light):
Current navigation drawer (dark):
New navigation drawer (light):
New navigation drawer (dark):
At least one DataGateway plugin needs to be loaded so that the navigation …

Small changes to navigation drawer #737

---

src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx

This fix ensures a consistent light or dark mode across all pages. A bug was causing SciGateway to remain in dark mode while the plugins were rendering in light mode. This can be seen when setting SciGateway to dark mode, navigating to one plugin route, which will be correctly themed, but navigating to other routes will cause a mix of light and dark mode.
The cause of this was established to be SciGateway constructing a theme for plugins with an erroneous dark mode value, despite the dark mode boolean in localStorage still being correct. Why this has suddenly started happening, I still don't know and I couldn't find any point in the code that caused this value to change. However, I identified a fix by simply moving the code that fetches the current dark mode value from localStorage …

Consistent theme across all pages #760

---

src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
src/mainAppBar/mainAppBar.component.test.tsx
src/mainAppBar/mainAppBar.component.tsx

This change allows for the logo that appears at the top of the page to automatically change based on which plugin the user is currently viewing. For example, if navigating to a DataGateway plugin, the logo should change to the DataGateway logo. This includes any custom homepage as this is loaded via a plugin itself, so will inherit that plugin logo. This solution is flexible so that no matter what future plugins are developed, as long as they provide a logo, it will be loaded.
This solution works by detecting which plugin ID can be found on the DOM. For example, if DataGateway Dataview is loaded, a `<div id="datagateway-dataview">` will exist. _If a plugin ID is found on the page but the plugin itself does not provide a logo or if no plugins ID is found on the page, then the SciGateway …

Logo dynamically changes based on currently loaded plugin #739

---

src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/authorisedRoute.component.test.tsx
src/routing/authorisedRoute.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx
src/state/state.types.tsx

This removes all functionality relating to the `startUrl` setting found in `settings.json`. None of this is required anymore due to the work done in https://github.com/ral-facilities/scigateway/pull/704 which redirects all traffic to a custom plugin homepage if set. `startUrl` was always used to redirect traffic that went directly to the website root to a set plugin path, e.g. `/browse/investigation`. However, this isn't required anymore because, in production, a custom homepage will always be set that we'll want to redirect to instead (or, failing that, the SciGateway homepage).
This PR removes all references to `startUrl` as well as any tests related to it. Also changing a couple of names in code to `homepageUrl` where relevant functionality overlaps (`homepageUrl` is the new setting …

Removing `startUrl` functionality and tests #708

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/contactPage/contactPage.component.tsx
src/cookieConsent/cookiesPage.component.tsx
src/footer/footer.component.tsx
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/helpPage/helpPage.component.tsx
src/theming.tsx

This fixes contrast issues with some of the URLs on https://github.com/ral-facilities/datagateway/issues/867 and https://github.com/ral-facilities/datagateway/issues/901, as well as fixing https://github.com/ral-facilities/datagateway/issues/898, https://github.com/ral-facilities/datagateway/issues/900, #793, #792. This also makes the dark mode background slightly darker in order to make it easier to make foreground colours compliant with WCAG 2.0.
Closes ral-facilities/datagateway#898, Closes ral-facilities/datagateway#900, Closes #793, Closes #792

Make dark mode background darker and links lighter (#795)

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/loginPage/loginPage.component.tsx
src/theming.tsx
src/tour/__snapshots__/tour.component.test.tsx.snap
src/tour/tour.component.test.tsx
src/tour/tour.component.tsx

This fixes addressed the following issues:
- Issue #790 - changed colour of button to be darker - the text colour in the button cannot be changed with react-joyride. Screenshots:
- Issue #791 - changed colour of warning text to be darker in light mode and lighter in dark mode. Screenshots: 
Closes #790, Closes #791

Some contrast fixes #795

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

This overrides the colour of the months/years in date pickers to fix contrast issues. This is related to https://github.com/ral-facilities/datagateway/pull/910.
The year header however does not seem to have an override and seems to require MUI v5 to fix.

Add overrides for year/month selector colours in date pickers (#795)

---

src/theming.tsx

Fix contrast issue with current day on date picker in dark mode as mentioned on #802 :

Override current day colour in dark mode (#795)

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

The error colour of instruction text next to the tick boxes on search don't have enough contrast on datagateway search.
<br><br>
closes #803

fixing the error colour for form labels #803

---

src/footer/footer.component.tsx

The bars in footer don't have sufficient contrast in dark mode 
<br><br>
closes #806

changed footer bar colour #806

---

public/res/default.json
src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/contactPage/contactPage.component.tsx
src/cookieConsent/cookieConsent.component.tsx
src/cookieConsent/cookiesPage.component.tsx
src/footer/footer.component.tsx
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/helpPage/helpPage.component.tsx
src/homePage/homePage.component.tsx
src/loginPage/loginPage.component.tsx
src/logoutPage/logoutPage.component.tsx
src/mainAppBar/__snapshots__/mainAppBar.component.test.tsx.snap
src/mainAppBar/mainAppBar.component.test.tsx
src/mainAppBar/mainAppBar.component.tsx
src/notifications/scigatewayNotification.component.tsx
src/pageNotFound/pageNotFound.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx
src/state/state.types.tsx
src/theming.tsx
src/tour/__snapshots__/tour.component.test.tsx.snap
src/tour/tour.component.tsx

Improves customisability of theme colours and adds high contrast settings that can be toggled using a button under the dark mode toggle. This requires PR https://github.com/ral-facilities/datagateway/pull/926.
High contrast dark mode example:
Closes #818

High contrast modes and improve theme customisation #795

---

src/App.tsx
src/authentication/baseAuthProvider.tsx
src/authentication/icatAuthProvider.test.tsx
src/authentication/icatAuthProvider.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/scigateway.types.tsx

This is so plugins can listen to this and perform actions such as cache invalidation.
If you want to test this, you need to login as two users with different data. I can show some gifs/do a demo of the different behaviours when using two users on DLS preprod data.
This is required by ral-facilities/datagateway#928

Broadcast signout action when user signs out

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

Overrides opacity of the placeholder text in outlined inputs which improves contrast and ensures the date pickers on DataGateway search look the same as the search textbox.
Closes #824

Make date picker placeholder the same as the search box (#824)

---

.github/dependabot.yml

Changes dependabot config to ignore patch versions. Corresponding DataGateway PR is here: https://github.com/ral-facilities/datagateway/pull/1026.

Modify dependabot config to ignore patch updates

---

public/res/default.json
src/footer/__snapshots__/footer.component.test.tsx.snap
src/footer/footer.component.tsx
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/homePage/__snapshots__/homePage.component.test.tsx.snap
src/homePage/homePage.component.tsx
src/loginPage/loginPage.component.tsx
src/mainAppBar/__snapshots__/userProfile.component.test.tsx.snap
src/mainAppBar/mainAppBar.component.tsx
src/mainAppBar/userProfile.component.tsx
src/navigationDrawer/navigationDrawer.component.tsx
src/notifications/notificationBadge.component.tsx
src/theming.tsx

Applies the tweaks described in https://github.com/ral-facilities/datagateway/issues/1048.
Also adds padding on the login page:
as previously this looked like:
on diamond.
Connect to ral-facilities/datagateway#1048

Homepage redesign tweaks #897

---

src/navigationDrawer/navigationDrawer.component.tsx

The navigation drawer logo should be set by the width of the of navigation bar 
closes #964

Navigation drawer logo is defined by width instead of the height #964

---

src/index.css

- Changing the min-width to a same size as the main app bar.
- To avoid getting this weird behaviour when "fit-content" is using
<br><br>
<br><br>
Check if the black bar (on the right-hand side) exist at maximum of the browser zoom (e.g. %500) 
closes #965

Changing the min-width to work correctly with card view #965

---

public/res/default.json
src/accessibilityPage/accessibilityPage.component.tsx

Addressing minor accessibility tweaks
-  updating the date (last reviewed)
- making the email render as a mailto link 
- removing duplicate of non-accessible content title and changed with the correct header 
- using rough time for "non-compliance with the accessibility regulations"
- rendering the domains URLs  as links 
closes #986

accessibility page minor tweaks #986

---

cypress/plugins/index.js
cypress/support/index.js
package.json
src/adminPage/adminPage.component.tsx
src/preloader/__snapshots__/preloader.component.test.tsx.snap
src/preloader/preloader.component.tsx
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx
src/state/actions/loadMicroFrontends.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
yarn.lock

After a lot of debugging and page refreshing to try and trigger the bug with logging, I think it was caused by `singleSpa.start()` being called before plugins had a chance to send their routes and thus make single-spa aware of them. Fixed by moving the `singleSpa.start()` call in the attempt to wait for plugins to send their routes section of `configureSite`.
Also, if the plugins are really slow I've added in a `triggerAppChange` call in the middleware.
EDIT: After noticing the bug still sometimes occurred, and a bug in that when the admin download table was directly accessed it loaded infinitely, I have added a "general" fix i.e. a setInterval that basically polls until the plugin routes has loaded, and checks if the preloader exists and if it does it calls `singleSpa.unloadApplication` …

Fix plugin loading bug

---

public/settings.example.json
src/accessibilityPage/__snapshots__/contactUs.component.test.tsx.snap
src/accessibilityPage/accessibilityPage.component.test.tsx
src/accessibilityPage/accessibilityPage.component.tsx
src/accessibilityPage/contactUs.component.test.tsx
src/accessibilityPage/contactUs.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx
src/state/state.types.tsx

I have successfully created two separate Contact Us forms for the accessibility page using Microsoft Forms, one for ISIS and one for Diamond. However, it comes with a lot of external reliance. These are the biggest problems and we'll need to think about whether we want to fix these somehow or just work with them as they are:
- The form is an embedded Microsoft Form, owned and managed by **my** Microsoft account. If the form is ever deleted or access to it is lost for whatever reason, this would invalidate the `src` for the `<iframe>` form object, which creates an `<iframe>` with a 404 Not Found DataGateway page
- Only the form owner receives the responses from the form, meaning by default I receive the responses at sam.glendenning@stfc.ac.uk. To bypass this, I've created two flows in …

Adding Contact Us form for accessibility enquiries #990

---

src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.test.tsx
src/navigationDrawer/navigationDrawer.component.tsx
src/state/scigateway.types.tsx

DOI redirect is a route that needs to not be in the nav drawer, so parse a boolean from the register route config to add that functionality
Connects to https://github.com/ral-facilities/datagateway/issues/1198

Hide plugin routes from menu

---

.github/dependabot.yml
.github/workflows/docker-build.yml

Creates a [GitHub Actions workflow](https://github.com/ral-facilities/scigateway/actions/workflows/docker-build.yml) for building and pushing the `Dockerfile` to the SCD Harbor Docker registry. It uses a Harbor robot account whose credentials are stored as secrets in this repo.
closes #1030

Create Actions workflow for uploading container image to Harbor

---

cypress/integration/login.spec.ts
src/mainAppBar/mainAppBar.component.tsx
src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/authorisedRoute.component.test.tsx
src/routing/authorisedRoute.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx

The user's login state now has no effect on access to the homepage or display of the navigation drawer. This means that, like ISIS, DLS now allows access to the homepage at the web root and the navigation drawer shows all web app routes (but no access allowed while not logged in). This is in comparison to how things used to work on DLS, whereby all nav drawer routes including the homepage were inaccessible until the user logged in.
This PR also includes a fix to a problem where the user would not be redirected to their original request following a successful login, instead being redirected to the homepage. This took a lot of trial and error but I came to the conclusion that this was because the current method detailed below no longer works:
- User tries to navigate to `/protected/domain` …

Homepage accessible regardless of login status #1049

---

cypress/integration/login.spec.ts
cypress/integration/scigateway_frontend_spec.tsx
src/mainAppBar/mainAppBar.component.tsx
src/state/reducers/scigateway.reducer.tsx

Basically I just removed the check for logged in users (and also for the login page as I figured we can just have the menu open everywhere by default for simplicity). Also stopped the drawer from closing on token invalidation.
Closes #1061

#1061 - have menu open by default no matter if you're logged in or not

---

public/res/default.json
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx

Goes with ral-facilities/datagateway#1262
Allow plugins to send a notification payload alongside their token invalidation request event, which we then only display after the token refresh has failed.
Part of the fix for ral-facilities/datagateway#1257

Fix token refresh error

---

cypress/integration/login.spec.ts
public/settings.example.json
src/authentication/icatAuthProvider.test.tsx
src/authentication/icatAuthProvider.tsx
src/loginPage/loginPage.component.test.tsx
src/loginPage/loginPage.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx

See title.
Also removed the `authUrl` argument from `verifyUsernameAndPassword` because it doesn't change so we can just reuse the old value
Closes #1081

#1081 - add autoLogin setting to control whether we attempt autoLogin

---

src/mainAppBar/mainAppBar.component.tsx

Instead, we just set a sensible max height based off of the app bar height. Default logos I set to be 24px height instead so we don't have to modify the SVGs to be smaller.
Closes #1086

#1086 - enable custom logos to be larger than 24px

---

package.json
src/setupTests.ts
yarn.lock

This PR adds the following `@testing-library` dependencies in order to start our migration from `enzyme` to `testing-library`:
- `@testing-library/react`
- `@testing-library/jest-dom`
- `@testing-library/user-event`
connect to #1141 
Closes #1141

Add @testing-library dependencies

---

package.json
yarn.lock

Following [the addition of @testing-library/react v13.x to SciGateway](https://github.com/ral-facilities/scigateway/pull/1171), a mismatch occurred due to v13+ [dropping support for React 17](https://github.com/testing-library/react-testing-library/pull/1031), the current version of SciGateway. As React 18 is not on the horizon yet for SciGateway, we need to ensure support for RTL in SciGateway.
Check tests pass and RTL <13.x is used
Hotfix

Downgrading @testing-library/react to v12.1.5

---

yarn.lock

The package is functional-red-black-tree. This seemed to occur when I merged the package update to eslint. See the job output here: https://github.com/ral-facilities/scigateway/actions/runs/3135039062/jobs/5105040029
The CI tests should pass
Hotfix

Updating yarn.lock to remove unnecessary package

---

.github/workflows/ci-build.yml
.github/workflows/release-build.yml

Hotfix to bump the version of Node used in CI from v14.x to v16.x, in line with https://github.com/ral-facilities/datagateway/pull/1513. 
hotfix, connect to nowhere.

Bump node version in CI from v14 to v16

---

public/res/default.json
src/App.test.tsx
src/__snapshots__/pageContainer.test.tsx.snap
src/authentication/testAuthProvider.tsx
src/homePage/__snapshots__/homePage.component.test.tsx.snap
src/homePage/homePage.component.test.tsx
src/homePage/homePage.component.tsx
src/index.css
src/mainAppBar/mainAppBar.component.test.tsx
src/mainAppBar/mainAppBar.component.tsx
src/mainAppBar/mobileOverflowMenu.component.test.tsx
src/mainAppBar/mobileOverflowMenu.component.tsx
src/mainAppBar/pageLinks.component.tsx
src/mainAppBar/settingsMenu.component.tsx
src/mainAppBar/styles.ts
src/navigationDrawer/navigationDrawer.component.test.tsx
src/navigationDrawer/navigationDrawer.component.tsx
src/pageContainer.component.tsx
src/pageContainer.test.tsx
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx

This PR improves scigatway mobile support by tweaking the overall UI layout on mobile. The following components are modified:
- Top app bar
- Drawer
- Home page
- Footer
The app bar contains several elements:
- Drawer button
- Website logo
- Page links (e.g. admin page, help page)
- Action buttons (tutorial, settings, etc.)
- User avatar
- Notifications
This is fine on larger viewports, but on smaller viewports there is not enough space to show everything at once. This PR introduces a new mobile overflow menu that consolidates page links, action buttons, and the settings menu into a single menu, accessible through a new menu overflow button that is only visible on small viewports. The app bar retains the current layout on larger viewports.
New mobile overflow menu:
Currently, on larger …

Improve scigateway mobile support

---

cypress/e2e/login.cy.ts
src/adminPage/maintenancePage.component.test.tsx
src/adminPage/maintenancePage.component.tsx
src/authentication/testAuthProvider.tsx
src/index.css
src/notifications/__snapshots__/scigatewayNotification.component.test.tsx.snap
src/notifications/scigatewayNotification.component.test.tsx
src/notifications/scigatewayNotification.component.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.test.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx

It is now possible to choose a severity for the scheduled maintenance pop-up in the admin interface. 
Added a new 'information' severity. 
Added unit tests to include cases for the 'information' in invalid severity. Updated tests to select severity from the selection list.
connect to #1053

Add severity selection to admin scheduledMaintenance #1053

---

src/App.test.tsx
src/App.tsx

Check for maintenance status every 5 minutes. If the status has changed from true to false - force refresh the page.
Updated unit tests in `App.test.tsx` to check for page reloads.
connect to #1312

Check for maintenance state every 5 minutes and force refresh if changed

---

src/adminPage/adminPage.component.test.tsx
src/adminPage/adminPage.component.tsx
src/authentication/nullAuthProvider.test.tsx
src/authentication/nullAuthProvider.tsx
src/mainAppBar/mainAppBar.component.tsx
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx
src/state/actions/scigateway.actions.tsx
src/state/reducers/scigateway.reducer.test.tsx
src/state/reducers/scigateway.reducer.tsx
src/state/scigateway.types.tsx
src/state/state.types.tsx

Created nullAuthProvider which allows to disable authentication related functionality when `"auth-provider": null` is specified in SG settings. 
Also, plugin routes can now be unauthenticated by specifying the optional `unauthorised: true` argument in plugin route settings. Plugin routes are authenticated by default.
Updated unit tests to check for redirections and remounting. Added a new test suite for nullAuthProvider.
connect to #1313

Feature/non authentication #1313

---

.github/workflows/ci-build.yml
Dockerfile

This PR pins the base docker images in the Dockerfiles to commit SHAs so that Renovate (or Dependabot if Renovate doesn't work) can create PRs each time there is a change in the upstream base images that the base images are set to use as new SHAs are generated on every upstream change. Not sure if Renovate will also update the OS versions but if it doesn't then we will have to do the Alpine version updates manually for now.
Please note that I have pinned it to an older SHA to verify that Renovate (or Dependabot if Renovate doesn't work) will create a PR.

Pin docker base images to SHA

---

src/__snapshots__/pageContainer.test.tsx.snap
src/footer/__snapshots__/footer.component.test.tsx.snap
src/footer/footer.component.tsx
src/mainAppBar/mainAppBar.component.tsx
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/routing.component.tsx

Ensures the main app bar and footer are excluded from printing. Also ensures a scrollbar is not used which previously prevented a second page from appearing in the print leading to a cut off.
I purposefully left out the navigation drawer as it also shifts everything right, so I thought it could be undesirable to hide it here as then the user may not realise why everything is shifted. They can close the app bar to hide it instead.
Closes https://github.com/ral-facilities/inventory-management-system/issues/439

Print improvement for IMS

---

src/theming.tsx

Resolves issue here: https://github.com/ral-facilities/inventory-management-system/issues/465.
This was caused because we override the error colours for various components but not generally when using the error colour directly. This adds in the override so they are all consistent. This could potentially have an undesired effect on datagateway if using `color="error"`, but I don't think it is being used anywhere I could find, and will only be going in the react-18 branch for the time being anyway,
Closes ral-facilities/inventory-management-system#465

Fix error colour inconsistency for IMS

---

Dockerfile
package.json
yarn.lock

Bumps the `node` Docker image from `20.11.1-alpine3.19` to `20.14.0-alpine3.20` and the `httpd` Docker image from `2.4.58-alpine3.19` to `2.4.59-alpine3.20`. It also bumps the project `@types/node` dependency from `20.11.5` to `20.14.0`.

Bump Docker base images

---

.github/release.yml
.github/workflows/release-build.yml

The old release action is a) unmaintained and b) always failed to upload the assets when the release was first created and thus the job needed to be reran. This fixes both those issues.
I tested this on my fork so feel free to verify it works: https://github.com/louise-davies/scigateway
This will also auto-trigger github to fill in it's generated release notes - it also adds a tiny bit of config to that to separate out dependency updates

Update release workflow

---

.github/workflows/ci-build.yml
.github/workflows/docker-release-build.yml

Adds a docker release action that builds and pushes the docker image when a tag is pushed. 
- I tested the `docker/metadata-action` part of this new action on my own repo and found the following behaviour:
| GitHub Tag | Docker Image Tags |
| ------------- | ------------- |
| v1.0.1  | 1.0, 1.0.1, v1.0.1 |
| v1.0.1-dev | 1.0.1-dev, v1.0.1-dev |
| 1.0.1 | 1.0, 1.0.1 |
| 1.0.1-dev | 1.0.1-dev |
| docker-test | docker-test |
- We use the additional `type=semver,pattern={{major}}.{{minor}}` tag on IMS so our docker compose doesn't need to be updated for a patch update and can instead just point to `1.0` so I have done the same here
- `latest` is disabled here as it would otherwise always be added with tags that do not follow the semver format and we don't use it at the moment anyway. If it is …

Add docker image push when tags pushed #1390

---

.github/workflows/ci-build.yml
.github/workflows/release-build.yml

Github changed the default machine from Ubuntu 22 to Ubuntu 24, which doesn't have libgconf-2-4. Equally, Cypress no longer needs this dependency so it can just be removed

Remove libgconf install step on CI jobs

---

Dockerfile

Updates node to 20.18.3-alpine3.21 and httpd to 2.4.63-alpine3.21 in docker images.

Update node to 20.18.3-alpine3.21 and httpd to 2.4.63-alpine3.21 in docker images
