ral-facilities/scigateway

src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.tsx

Fixed the forward ref errors in the console from the ListLinkItem. 
Closes #140

Fix LinkListItem with a forwardRef Link (#140)

---

codecov.yml

Reduce patch coverage to 75% as discussed (patch coverage is the coverage of the code in the PR only)

Update codecov patch target to 75%

---

.eslintrc.js
cypress/integration/scigateway_frontend_spec.tsx
src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap
src/routing/__snapshots__/routing.component.test.tsx.snap
src/routing/authorisedRoute.component.tsx
src/routing/routing.component.test.tsx
src/routing/routing.component.tsx

Fix the 404 page bug that was introduced by #194. I've changed which component is the pure component - now it's the plugin div itself and not the route, and this seems to fix things with the 404. Additionally, I added extra e2e tests that will hopefully catch problems with the 404 page or plugin rerendering in the future.
Closes #222

Fix 404 page

---

package.json

Removes the "git add" from `package.json`.
Closes #475

Remove git add in package.json

---

src/state/actions/scigateway.actions.tsx

Check if the plugins property exists and it is not empty when loading `setttings.json`.
Closes #570

Add plugins check in configureSite (#570)

---

src/adminPage/adminPage.component.test.tsx
src/adminPage/adminPage.component.tsx
src/authentication/icatAuthProvider.test.tsx
src/authentication/icatAuthProvider.tsx
src/authentication/testAuthProvider.tsx
src/state/actions/scigateway.actions.test.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/state.types.tsx

Add maintenance notification when SciGateway is currently in maintenance mode.
Closes #734, closes #750

Feature/maintenance notification #734

---

src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.tsx

Update the aria-label on the navigation drawer close button.
Closes #754

Update navigation drawer aria-label (#754)

---

public/res/default.json
src/homePage/__snapshots__/homePage.component.test.tsx.snap
src/homePage/homePage.component.tsx

Added the alt text for the images and it is read out correctly by the screen reader.
Closes #753

Added the alt text to homepage images from the default.json file #753

---

public/index.html
src/index.tsx

This means we can have an icinga check based on this div (which is only used for telling React where to load, and nothing user facing) rather than the title (which is user facing and thus we'd like to be able to configure)
Closes #799

#799 - change id of base div from root to scigateway

---

src/contactPage/__snapshots__/contactPage.component.test.tsx.snap
src/global.d.ts
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

Overrides the date picker theme to improve the contrast. This helps with https://github.com/ral-facilities/datagateway/pull/910 but does not in itself fix the issue.

Override date picker theme (#795)

---

src/navigationDrawer/__snapshots__/navigationDrawer.component.test.tsx.snap
src/navigationDrawer/navigationDrawer.component.tsx

Fixes issue described in #808 by changing the headings to Typography components and removing the outer list element so that no list directly contains a 'nav' element. I have also checked the keyboard navigation behaviour to make sure it is the same.
Check menu looks and behaves the same as before.
Closes #808

Fix navigation drawer list structure (#808)

---

src/logoutPage/__snapshots__/logoutPage.component.test.tsx.snap
src/logoutPage/logoutPage.component.test.tsx
src/logoutPage/logoutPage.component.tsx
src/pageNotFound/__snapshots__/pageNotFound.component.test.tsx.snap
src/pageNotFound/pageNotFound.component.test.tsx
src/pageNotFound/pageNotFound.component.tsx
src/routing/__snapshots__/authorisedRoute.component.test.tsx.snap

- Correct one of the test id in the logout to be more consistence with the other test ids.
- Added more testing to the page not found page.  
closes #810

 The 404 pages in dark mode don't have enough contrast  #810

---

src/theming.tsx

Overrides colour of form label focus and the corresponding underline in dark mode.
Closes ral-facilities/datagateway#921

Add overrides for role selector (#795)

---

src/loginPage/__snapshots__/loginPage.component.test.tsx.snap
src/loginPage/loginPage.component.tsx

Adding aria labels to the login page for screen readers.
Test using a Screen reader to check it's human-readable 
closes #813

adding aria labels to the login page #813

---

public/res/default.json
src/footer/footer.component.tsx
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

As part of the homepage redesign ral-facilities/datagateway#954, modify the footer to match the UX pin design below:
https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/144657834/simulate/no-panels
check footer in the various contrast mode to see if they satisfy WCAG 2.1 guidelines (https://github.com/ral-facilities/scigateway/pull/819)
closes #850

footer redesign #850

---

public/res/default.json
src/footer/__snapshots__/footer.component.test.tsx.snap
src/footer/footer.component.tsx
src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

Adding extra information in the footer:
- 'Privacy statement' pointing to information such as the one at: https://stfc.ukri.org/about-us/privacy-statement/
- 'Data policy' pointing to the ISIS data policy
- 'Built by the **Data and Software Engineering Group**'
ral-facilities/datagateway/issues/1003
closes #850, ral-facilities/datagateway/issues/1003

footer information #850

---

public/res/default.json
src/loginPage/__snapshots__/loginPage.component.test.tsx.snap
src/loginPage/loginPage.component.tsx
src/logoutPage/logoutPage.component.tsx
src/routing/routing.component.test.tsx

Adding more information onto the Login (Please look below for design)
- https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/145182791/simulate/no-panels
- Check spacing matches with the UXpin and https://github.com/ral-facilities/scigateway/issues/864
- Check with screen reader  
closes #864

Feature/adding info loginpage#864

---

src/index.css

The colours of the toasts (Warning and error) do not have enough contrast to satisfy WCAG contrast  
connect to #{issue number}

Changing the toast colours #825

---

src/helpPage/__snapshots__/helpPage.component.test.tsx.snap
src/theming.tsx

Applies theming changes required by https://github.com/ral-facilities/datagateway/pull/1068.
Test with https://github.com/ral-facilities/datagateway/pull/1068.
Closes #910

Apply theming changes (#910)

---

src/loginPage/loginPage.component.test.tsx
src/loginPage/loginPage.component.tsx

Added the new error message suggested by Alejandra https://github.com/ral-facilities/scigateway/issues/914#issue-1109268536
Closes #914

Added the new message suggested in the issue #914

---

src/cookieConsent/cookieConsent.component.test.tsx
src/cookieConsent/cookieConsent.component.tsx
src/cookieConsent/cookiesPage.component.tsx

Adding same site to the cookie flag to stop the warning message appearing on Firefox.
closes #975

Fix cookie warning in firefox #975

---

src/mainAppBar/userProfile.component.tsx

Changing the colour of the account icon so match other buttons in the main app bar 
closes #983

changing the account icon button #983

---

src/pageNotFound/__snapshots__/pageNotFound.component.test.tsx.snap
src/pageNotFound/pageNotFound.component.test.tsx
src/pageNotFound/pageNotFound.component.tsx

#1013 - change link in 404 page to same as contact link in footer

---

src/navigationDrawer/navigationDrawer.component.tsx
src/routing/routing.component.tsx
src/state/actions/scigateway.actions.tsx
src/state/middleware/scigateway.middleware.tsx
src/state/reducers/scigateway.reducer.tsx

This is necessary to fix ral-facilities/datagateway#1199.
Goes with ral-facilities/datagateway#1203

Allow for plugin links to have query params in them

---

.github/workflows/ci-build.yml
.github/workflows/release-build.yml
README.md

Following the renaming of master to main, here we're modifying some old references to master

Rename master to main

---

CHANGELOG.md
package.json

Updating the version number in `package.json` to indicate the `v1.0.0` release

Update version number

---

.dockerignore
Dockerfile
docker/docker-entrypoint.sh
docker/settings.json

- Uses cache mount to speed up fetching of yarn dependencies
- Creates a settings file in the `docker` directory that has all the DataGateway plugins enabled and uses this in the image
- Adds ability for `AUTH_PROVIDER` and `AUTH_URL` to be provided as env vars
- Adds an entypoint script that takes the values of the env vars and updates the settings file accordingly

Docker image improvements

---

.github/workflows/ci-build.yml
.github/workflows/release-build.yml

Update Node version to 20 in CI

---

Dockerfile

Upgrades the version of Node to 20.

Upgrade Node
